language: python
cache: pip
dist: xenial
python:
{%- if cookiecutter.py2_support.lower() == 'y' %}
  - "2.7"
{%- endif %}
  - "3.6"
  - "3.7"
  - "3.8"
{%- if cookiecutter.use_django.lower() == 'y' %}
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
{%- endif %}
install: pip install tox-travis codecov
{%- if cookiecutter.use_django.lower() == 'y' %}
matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: TOXENV=lint }
{% if cookiecutter.py2_support.lower() == 'y' %}
    - { python: "2.7", env: DJANGO=1.11 }
{% endif %}
    - { python: "3.6", env: DJANGO=1.11 }
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: DJANGO=2.1 }
    - { python: "3.6", env: DJANGO=2.2 }
    - { python: "3.6", env: DJANGO=3.0 }
    - { python: "3.6", env: DJANGO=master }

    - { python: "3.7", env: DJANGO=1.11 }
    - { python: "3.7", env: DJANGO=2.0 }
    - { python: "3.7", env: DJANGO=2.1 }
    - { python: "3.7", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=3.0 }
    - { python: "3.7", env: DJANGO=master }

    - { python: "3.8", env: DJANGO=1.11 }
    - { python: "3.8", env: DJANGO=2.0 }
    - { python: "3.8", env: DJANGO=2.1 }
    - { python: "3.8", env: DJANGO=3.0 }
    - { python: "3.8", env: DJANGO=master }
{%- endif %}
script:
{%- if cookiecutter.use_django.lower() == 'n' %}
  - tox -e lint
{%- endif %}
  - tox
notifications:
  email: false
after_success:
  - codecov
